# Generated by Django 5.0.6 on 2024-06-14 16:28

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('direccion1', models.CharField(blank=True, default='', help_text='(Calle, nro, comuna)', max_length=200, verbose_name='Dirección')),
                ('direccion2', models.CharField(blank=True, default='', help_text='(Departamento, casa, etc.)', max_length=200, null=True, verbose_name='Dirección 2')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Teléfono')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='usuarios', verbose_name='Imagen')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Empleado')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superusuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
