# Generated by Django 5.0.6 on 2024-07-01 18:29

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_direccion1_remove_usuario_direccion2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion1', models.CharField(max_length=255, verbose_name='Dirección')),
                ('direccion2', models.CharField(blank=True, help_text='(Departamento, casa, etc.)', max_length=255, null=True, verbose_name='Dirección 2')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(help_text='(Ej: +56912345678 o 912345678)', max_length=128, region='CL', verbose_name='Teléfono')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
