# Generated by Django 5.0.6 on 2024-07-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='cod_postal',
            field=models.CharField(default='a', max_length=10, verbose_name='Código postal'),
            preserve_default=False,
        ),
    ]
