# Generated by Django 5.0.6 on 2024-07-04 02:43

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_direccion_cod_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='(Ej: 912345678)', max_length=128, region='CL', verbose_name='Teléfono'),
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número de tarjeta')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del titular')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('cvv', models.IntegerField(verbose_name='CVV')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
