# Generated by Django 5.0.6 on 2024-07-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_direccion_telefono_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento',
            field=models.CharField(help_text='(MM/AA)', max_length=5, verbose_name='Fecha de vencimiento'),
        ),
    ]
