# Generated by Django 5.0.6 on 2024-06-22 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagina.fabricante', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta_Grafica',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pagina.producto')),
                ('memoria', models.PositiveIntegerField(verbose_name='Memoria')),
                ('bus', models.CharField(max_length=50, verbose_name='Bus')),
                ('perfil', models.CharField(max_length=50, verbose_name='Perfil')),
                ('slots', models.CharField(max_length=50, verbose_name='Slots')),
                ('largo', models.PositiveIntegerField(help_text='En mm', verbose_name='Largo')),
                ('puertos', models.CharField(max_length=100, verbose_name='Puertos de video')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagina.gpu', verbose_name='GPU')),
            ],
            options={
                'verbose_name': 'Tarjeta Gráfica',
                'verbose_name_plural': 'Tarjetas Gráficas',
            },
            bases=('pagina.producto',),
        ),
    ]
