# Generated by Django 5.0.6 on 2024-06-25 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
            },
        ),
        migrations.CreateModel(
            name='FuenteAlimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.ImageField(blank=True, null=True, upload_to='productos/descripciones', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
                ('potencia', models.PositiveIntegerField(help_text='En W', verbose_name='Potencia')),
                ('eficiencia', models.CharField(max_length=50, verbose_name='Eficiencia')),
                ('certificacion', models.CharField(max_length=50, verbose_name='Certificación')),
                ('modular', models.BooleanField(verbose_name='Modular')),
            ],
            options={
                'verbose_name': 'Fuente de Alimentación',
                'verbose_name_plural': 'Fuentes de Alimentación',
            },
        ),
        migrations.CreateModel(
            name='Gabinete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.ImageField(blank=True, null=True, upload_to='productos/descripciones', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
                ('tam_placa', models.CharField(default='ATX', max_length=50, verbose_name='Tamaño máximo de la placa')),
                ('fuente', models.CharField(default='Inferior', max_length=50, verbose_name='Ubicación fuente')),
                ('vent_inc', models.CharField(default='No posee', max_length=100, verbose_name='Ventiladores incluidos')),
                ('esp_vent_front', models.CharField(default='3 x 120 mm', max_length=100, verbose_name='Espacios para ventiladores frontales')),
                ('esp_vent_top', models.CharField(default='2 x 120 mm', max_length=100, verbose_name='Espacios para ventiladores superiores')),
                ('esp_vent_back', models.CharField(default='1 x 120 mm', max_length=100, verbose_name='Espacios para ventiladores traseros')),
                ('esp_vent_bottom', models.CharField(default='No posee', max_length=100, verbose_name='Espacios para ventiladores inferiores')),
                ('puertos', models.CharField(blank=True, max_length=100, verbose_name='Puertos')),
            ],
            options={
                'verbose_name': 'Gabinete',
                'verbose_name_plural': 'Gabinetes',
            },
        ),
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.ImageField(blank=True, null=True, upload_to='productos/descripciones', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
                ('capacidad', models.PositiveIntegerField(help_text='En GB', verbose_name='Capacidad')),
                ('lectura', models.PositiveIntegerField(help_text='En MB/s', verbose_name='Lectura')),
                ('escritura', models.PositiveIntegerField(help_text='En MB/s', verbose_name='Escritura')),
                ('formato', models.CharField(max_length=50, verbose_name='Formato')),
            ],
            options={
                'verbose_name': 'Disco Duro',
                'verbose_name_plural': 'Discos Duros',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='MemoriaRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.ImageField(blank=True, null=True, upload_to='productos/descripciones', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
                ('capacidad', models.PositiveIntegerField(help_text='En GB', verbose_name='Capacidad')),
                ('frecuencia', models.PositiveIntegerField(help_text='En MHz', verbose_name='Frecuencia')),
                ('latencia', models.CharField(max_length=50, verbose_name='Latencia')),
                ('formato', models.CharField(max_length=50, verbose_name='Formato')),
            ],
            options={
                'verbose_name': 'Memoria',
                'verbose_name_plural': 'Memorias',
            },
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Socket',
                'verbose_name_plural': 'Sockets',
            },
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.ImageField(blank=True, null=True, upload_to='productos/descripciones', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
                ('capacidad', models.PositiveIntegerField(help_text='En GB', verbose_name='Capacidad')),
                ('lectura', models.PositiveIntegerField(help_text='En MB/s', verbose_name='Lectura')),
                ('escritura', models.PositiveIntegerField(help_text='En MB/s', verbose_name='Escritura')),
                ('formato', models.CharField(max_length=50, verbose_name='Formato')),
                ('interfaz', models.CharField(max_length=50, verbose_name='Interfaz')),
            ],
            options={
                'verbose_name': 'SSD',
                'verbose_name_plural': 'SSDs',
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pagina.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'GPU',
                'verbose_name_plural': 'GPUs',
            },
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.ImageField(blank=True, null=True, upload_to='productos/descripciones', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
                ('nucleos', models.PositiveIntegerField(verbose_name='Núcleos')),
                ('hilos', models.PositiveIntegerField(verbose_name='Hilos')),
                ('frecuencia', models.FloatField(help_text='En GHz', verbose_name='Frecuencia')),
                ('turbo', models.FloatField(help_text='En GHz', verbose_name='Turbo')),
                ('cache', models.FloatField(help_text='En MB', verbose_name='Cache')),
                ('tdp', models.PositiveIntegerField(help_text='En W', verbose_name='TDP')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pagina.marca', verbose_name='Marca')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagina.socket', verbose_name='Socket')),
            ],
            options={
                'verbose_name': 'Procesador',
                'verbose_name_plural': 'Procesadores',
            },
        ),
        migrations.CreateModel(
            name='PlacaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.ImageField(blank=True, null=True, upload_to='productos/descripciones', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
                ('formato', models.CharField(max_length=50, verbose_name='Formato')),
                ('ram', models.PositiveIntegerField(help_text='En GB', verbose_name='RAM')),
                ('slots_ram', models.PositiveIntegerField(verbose_name='Slots de RAM')),
                ('slots_m2', models.PositiveIntegerField(verbose_name='Slots M.2')),
                ('slots_sata', models.PositiveIntegerField(verbose_name='Slots SATA')),
                ('puertos_usb', models.PositiveIntegerField(verbose_name='Puertos USB')),
                ('puertos_video', models.PositiveIntegerField(verbose_name='Puertos de video')),
                ('puertos_red', models.PositiveIntegerField(verbose_name='Puertos de red')),
                ('puertos_audio', models.PositiveIntegerField(verbose_name='Puertos de audio')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagina.socket', verbose_name='Socket')),
            ],
            options={
                'verbose_name': 'Placa Base',
                'verbose_name_plural': 'Placas Base',
            },
        ),
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.ImageField(blank=True, null=True, upload_to='productos/descripciones', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
                ('rpm', models.PositiveIntegerField(verbose_name='RPM')),
                ('flujo', models.PositiveIntegerField(help_text='En CFM', verbose_name='Flujo de aire')),
                ('ruido', models.PositiveIntegerField(help_text='En dBA', verbose_name='Ruido')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagina.socket', verbose_name='Socket')),
            ],
            options={
                'verbose_name': 'Cooler',
                'verbose_name_plural': 'Coolers',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta_Grafica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.ImageField(blank=True, null=True, upload_to='productos/descripciones', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
                ('memoria', models.PositiveIntegerField(help_text='En GB', verbose_name='Memoria')),
                ('bus', models.CharField(max_length=50, verbose_name='Bus')),
                ('perfil', models.CharField(max_length=50, verbose_name='Perfil')),
                ('slots', models.CharField(max_length=50, verbose_name='Slots')),
                ('largo', models.PositiveIntegerField(help_text='En mm', verbose_name='Largo')),
                ('puertos', models.CharField(max_length=100, verbose_name='Puertos de video')),
                ('fabricante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pagina.fabricante', verbose_name='Fabricante')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagina.gpu', verbose_name='GPU')),
            ],
            options={
                'verbose_name': 'Tarjeta Gráfica',
                'verbose_name_plural': 'Tarjetas Gráficas',
            },
        ),
    ]
