# Generated by Django 5.0.6 on 2024-06-25 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placabase',
            name='ram',
        ),
    ]
