# Generated by Django 5.0.6 on 2024-06-25 04:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_remove_placabase_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooler',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de agregado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuentealimentacion',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de agregado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gabinete',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de agregado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hdd',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de agregado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoriaram',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de agregado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placabase',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de agregado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procesador',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de agregado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ssd',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de agregado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarjeta_grafica',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de agregado'),
            preserve_default=False,
        ),
    ]
