# Generated by Django 5.0.6 on 2024-06-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_cooler_fecha_agregado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdd',
            name='rpm',
            field=models.PositiveIntegerField(default=7200, verbose_name='RPM'),
            preserve_default=False,
        ),
    ]
