# Generated by Django 5.0.6 on 2024-06-26 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_cooler_stock_fuentealimentacion_stock_gabinete_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gabinete',
            name='esp_vent_back',
            field=models.CharField(max_length=100, verbose_name='Espacios para ventiladores traseros'),
        ),
        migrations.AlterField(
            model_name='gabinete',
            name='esp_vent_front',
            field=models.CharField(max_length=100, verbose_name='Espacios para ventiladores frontales'),
        ),
        migrations.AlterField(
            model_name='gabinete',
            name='esp_vent_top',
            field=models.CharField(max_length=100, verbose_name='Espacios para ventiladores superiores'),
        ),
        migrations.AlterField(
            model_name='gabinete',
            name='puertos',
            field=models.CharField(max_length=100, verbose_name='Puertos'),
        ),
        migrations.AlterField(
            model_name='gabinete',
            name='tam_placa',
            field=models.CharField(max_length=50, verbose_name='Tamaño máximo de la placa'),
        ),
        migrations.AlterField(
            model_name='tarjeta_grafica',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagina.fabricante', verbose_name='Fabricante'),
        ),
    ]
