# Generated by Django 5.0.6 on 2024-06-23 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pagina.producto')),
                ('socket', models.CharField(max_length=50, verbose_name='Socket')),
                ('rpm', models.PositiveIntegerField(verbose_name='RPM')),
                ('flujo', models.PositiveIntegerField(help_text='En CFM', verbose_name='Flujo de aire')),
                ('ruido', models.PositiveIntegerField(help_text='En dBA', verbose_name='Ruido')),
            ],
            options={
                'verbose_name': 'Cooler',
                'verbose_name_plural': 'Coolers',
            },
            bases=('pagina.producto',),
        ),
        migrations.CreateModel(
            name='FuenteAlimentacion',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pagina.producto')),
                ('potencia', models.PositiveIntegerField(help_text='En W', verbose_name='Potencia')),
                ('eficiencia', models.CharField(max_length=50, verbose_name='Eficiencia')),
                ('certificacion', models.CharField(max_length=50, verbose_name='Certificación')),
                ('modular', models.BooleanField(verbose_name='Modular')),
            ],
            options={
                'verbose_name': 'Fuente de Alimentación',
                'verbose_name_plural': 'Fuentes de Alimentación',
            },
            bases=('pagina.producto',),
        ),
        migrations.CreateModel(
            name='Gabinete',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pagina.producto')),
                ('formato', models.CharField(max_length=50, verbose_name='Formato')),
                ('fuente', models.CharField(max_length=50, verbose_name='Fuente')),
                ('ventiladores', models.PositiveIntegerField(verbose_name='Ventiladores')),
                ('slots', models.PositiveIntegerField(verbose_name='Slots')),
                ('puertos_usb', models.PositiveIntegerField(verbose_name='Puertos USB')),
                ('puertos_audio', models.PositiveIntegerField(verbose_name='Puertos de audio')),
            ],
            options={
                'verbose_name': 'Gabinete',
                'verbose_name_plural': 'Gabinetes',
            },
            bases=('pagina.producto',),
        ),
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pagina.producto')),
                ('capacidad', models.PositiveIntegerField(help_text='En GB', verbose_name='Capacidad')),
                ('lectura', models.PositiveIntegerField(help_text='En MB/s', verbose_name='Lectura')),
                ('escritura', models.PositiveIntegerField(help_text='En MB/s', verbose_name='Escritura')),
                ('formato', models.CharField(max_length=50, verbose_name='Formato')),
                ('interfaz', models.CharField(max_length=50, verbose_name='Interfaz')),
            ],
            options={
                'verbose_name': 'Disco Duro',
                'verbose_name_plural': 'Discos Duros',
            },
            bases=('pagina.producto',),
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='MemoriaRam',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pagina.producto')),
                ('capacidad', models.PositiveIntegerField(help_text='En GB', verbose_name='Capacidad')),
                ('frecuencia', models.PositiveIntegerField(help_text='En MHz', verbose_name='Frecuencia')),
                ('latencia', models.CharField(max_length=50, verbose_name='Latencia')),
                ('formato', models.CharField(max_length=50, verbose_name='Formato')),
            ],
            options={
                'verbose_name': 'Memoria',
                'verbose_name_plural': 'Memorias',
            },
            bases=('pagina.producto',),
        ),
        migrations.CreateModel(
            name='PlacaBase',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pagina.producto')),
                ('formato', models.CharField(max_length=50, verbose_name='Formato')),
                ('socket', models.CharField(max_length=50, verbose_name='Socket')),
                ('ram', models.PositiveIntegerField(help_text='En GB', verbose_name='RAM')),
                ('slots_ram', models.PositiveIntegerField(verbose_name='Slots de RAM')),
                ('slots_m2', models.PositiveIntegerField(verbose_name='Slots M.2')),
                ('slots_sata', models.PositiveIntegerField(verbose_name='Slots SATA')),
                ('puertos_usb', models.PositiveIntegerField(verbose_name='Puertos USB')),
                ('puertos_video', models.PositiveIntegerField(verbose_name='Puertos de video')),
                ('puertos_red', models.PositiveIntegerField(verbose_name='Puertos de red')),
                ('puertos_audio', models.PositiveIntegerField(verbose_name='Puertos de audio')),
            ],
            options={
                'verbose_name': 'Placa Base',
                'verbose_name_plural': 'Placas Base',
            },
            bases=('pagina.producto',),
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pagina.producto')),
                ('nucleos', models.PositiveIntegerField(verbose_name='Núcleos')),
                ('hilos', models.PositiveIntegerField(verbose_name='Hilos')),
                ('frecuencia', models.FloatField(help_text='En GHz', verbose_name='Frecuencia')),
                ('turbo', models.FloatField(help_text='En GHz', verbose_name='Turbo')),
                ('cache', models.FloatField(help_text='En MB', verbose_name='Cache')),
                ('socket', models.CharField(max_length=50, verbose_name='Socket')),
                ('tdp', models.PositiveIntegerField(help_text='En W', verbose_name='TDP')),
            ],
            options={
                'verbose_name': 'Procesador',
                'verbose_name_plural': 'Procesadores',
            },
            bases=('pagina.producto',),
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pagina.producto')),
                ('capacidad', models.PositiveIntegerField(help_text='En GB', verbose_name='Capacidad')),
                ('lectura', models.PositiveIntegerField(help_text='En MB/s', verbose_name='Lectura')),
                ('escritura', models.PositiveIntegerField(help_text='En MB/s', verbose_name='Escritura')),
                ('formato', models.CharField(max_length=50, verbose_name='Formato')),
                ('interfaz', models.CharField(max_length=50, verbose_name='Interfaz')),
            ],
            options={
                'verbose_name': 'SSD',
                'verbose_name_plural': 'SSDs',
            },
            bases=('pagina.producto',),
        ),
        migrations.AlterModelOptions(
            name='gpu',
            options={'verbose_name': 'GPU', 'verbose_name_plural': 'GPUs'},
        ),
        migrations.AddField(
            model_name='gpu',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pagina.marca', verbose_name='Marca'),
        ),
    ]
