# Generated by Django 5.0.6 on 2024-06-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_alter_gabinete_esp_vent_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooler',
            name='flujo',
            field=models.FloatField(help_text='En CFM', verbose_name='Flujo de aire'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='ruido',
            field=models.FloatField(help_text='En dBA', verbose_name='Ruido'),
        ),
    ]
