# Generated by Django 5.0.6 on 2024-06-24 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_cooler_fuentealimentacion_gabinete_hdd_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hdd',
            name='interfaz',
        ),
    ]
