# Generated by Django 5.0.6 on 2024-06-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_remove_hdd_interfaz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.ImageField(blank=True, null=True, upload_to='productos/descripciones', verbose_name='Descripción'),
        ),
    ]
