# Generated by Django 5.0.6 on 2024-06-24 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_alter_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fabricante',
        ),
        migrations.AddField(
            model_name='procesador',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pagina.marca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='tarjeta_grafica',
            name='fabricante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pagina.fabricante', verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='tarjeta_grafica',
            name='memoria',
            field=models.PositiveIntegerField(help_text='En GB', verbose_name='Memoria'),
        ),
    ]
