# Generated by Django 5.0.6 on 2024-06-24 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_remove_producto_fabricante_procesador_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Socket',
                'verbose_name_plural': 'Sockets',
            },
        ),
        migrations.AlterField(
            model_name='cooler',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagina.socket', verbose_name='Socket'),
        ),
        migrations.AlterField(
            model_name='placabase',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagina.socket', verbose_name='Socket'),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagina.socket', verbose_name='Socket'),
        ),
    ]
