# Generated by Django 5.0.6 on 2024-07-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_carrito_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
    ]
