# Generated by Django 5.0.6 on 2024-06-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0010_socket_alter_cooler_socket_alter_placabase_socket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gabinete',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='gabinete',
            name='puertos_audio',
        ),
        migrations.RemoveField(
            model_name='gabinete',
            name='puertos_usb',
        ),
        migrations.RemoveField(
            model_name='gabinete',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='gabinete',
            name='ventiladores',
        ),
        migrations.AddField(
            model_name='gabinete',
            name='esp_vent_back',
            field=models.CharField(default='1 x 120 mm', max_length=100, verbose_name='Espacios para ventiladores traseros'),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='esp_vent_bottom',
            field=models.CharField(default='No posee', max_length=100, verbose_name='Espacios para ventiladores inferiores'),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='esp_vent_front',
            field=models.CharField(default='3 x 120 mm', max_length=100, verbose_name='Espacios para ventiladores frontales'),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='esp_vent_top',
            field=models.CharField(default='2 x 120 mm', max_length=100, verbose_name='Espacios para ventiladores superiores'),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='puertos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Puertos'),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='tam_placa',
            field=models.CharField(default='ATX', max_length=50, verbose_name='Tamaño máximo de la placa'),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='vent_inc',
            field=models.CharField(default='No posee', max_length=100, verbose_name='Ventiladores incluidos'),
        ),
        migrations.AlterField(
            model_name='gabinete',
            name='fuente',
            field=models.CharField(default='Inferior', max_length=50, verbose_name='Ubicación fuente'),
        ),
    ]
