# Generated by Django 5.0.6 on 2024-07-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0010_alter_carrito_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
