# Generated by Django 5.0.6 on 2024-07-05 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0011_alter_carrito_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
    ]
