# Generated by Django 5.0.6 on 2024-07-09 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pagina', '0013_pedido_productopedido'),
        ('usuarios', '0009_usuario_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.direccion', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.tarjeta', verbose_name='Tarjeta'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='productopedido',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
    ]
